<a href="https://colab.research.google.com/github/KETHAVATHSUNITHA/Workforce-Retention-System/blob/main/my_numpy_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy


In [ ]:
#what is numpy?
#it is a core library for scientitive computing in python
#the central object in numpy is  numpy arrey's
#whta is numpy array?
#it is high performance multodimentional objects which is decigned specifically performe on maths operatuons



In [ ]:
#how many types of arrays ?
#three types
#1D array    :- axis 0(only rows)
#2D array    :- axis0(rows) and axis 1 (col)   tabular
#3D array    :- axis 0(rows) axis 1 (col) axis 2 (step) (rows,col=2)

In [ ]:
#what are all different use cases and mathematical operation that can be acheved esaily with numpy
"""1. Dot product / inner product
   2. Matrix multiplication
   3. element wise matrix product
   4. solving the liner system
   5. invsere
   6. determinent
   7. choose the random number(gussian / uniform distrubution)
   8. statistics"""

In [ ]:
#installation of numpy
#use PIP --means python package manager
! pip install numpy

In [ ]:
import numpy as np

In [ ]:
#how can we check the version of numpy
np.__version__

'1.26.4'

In [ ]:
#what is the difference between list and numpy array?
"""Array:- array can take homogenous data
           array's are faster than the list because these are immutable
           array's are having fixed memory"""

In [ ]:
#arrat's--> ordered , immutable also it allows the duplicates

** Central object in numpy is numpy array's

In [ ]:
a = np.array([1,2,3,4,5])
print(a)
#how can we create an array?
#array's are created from existing data(list , tuples , dictionary's)
#inwant know the shap of the array
a.shape
#i want know the element data types in array's
a.dtype
#i want to know the dimensions of the array
a.ndim
#i want to know the total number of element in the array
a.size
# print(len(a)) ---> we can use the length() also
#i want to know the size in bytes of each element
a.itemsize

[1 2 3 4 5]


8

In [ ]:
a= np.array([[1,2,3,4,5]])
print(a)
a.ndim

[[1 2 3 4 5]]


2

In [ ]:
a = np.array([[[[1,2,3,4,5]]]])
print(a)
a.ndim

[[[[1 2 3 4 5]]]]


4

#essential methods in NP

In [ ]:
#access and change the element in the array
b = np.array([1,2,3])
print(b[1])
print(b[::-1])

2
[3 2 1]


In [ ]:
#by using index position number we can replace the items from array
b[0] = 5
print(b)

[5 2 3]


#element wise math operation

In [ ]:
c = np.array([2,0,2])
print(b+c)
print(b-c)
print(b*c)
print(b/c)
#Note--> When applying arthematic operation on two array's. the arrays has to be in same length or size
#task--> apply all arthematic operation
#what is vector addition
#when applying addition operation to the array's of the same length is know as vector addition

In [ ]:
#i want know the sum of the element in an array
d= np.array([5,6,7])
print(d.sum())
#i want know the mini element in an array
print(d.min())
#i want know the max element in an array
print(d.max())

18
5
7


** Array's VS List

In [ ]:
import numpy as np
g= [1,2,3]
#create an array above list
a = np.array(g)
print(a)
#adding new item to the list
l.append(4)
#print(l)
#adding the new item to the array
d.append(5) # we cannot add the items in an array
#how can we add new items in the array
#if you want add new item to an array create a new array
al = d + np.array([5])
print(al)
#NOTE--> when you are adding another array to existing array it must be in same size or new array can have 1 element

In [ ]:
#find the square root of an below array
a2 = np.array([1,2,3,4,5])
print(np.sqrt(a2))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
a = "hello world"
a.size

AttributeError: 'str' object has no attribute 'size'

In [ ]:
l1 = ["amma","nanna","akkka"]
l_t = tuple
print(l_t)

<class 'tuple'>


**21-11-2024**

#dot product

In [ ]:
 #easy with numpy
 import numpy as np
 a = np.array([1,2])
 b = np.array([3,4])
 print(np.dot(a,b))

11


In [ ]:
a = np.array([1,2])
b = np.array([3,4])
dot = 0
for i in range(len(a)):
  dot += a[i]*b[i]
print(dot)
#vector multiplication of array's and sum of elements of the result
#multiple each corresponding element and make sum


11


In [ ]:
#broadcasting method
p = np.array([1,2,5])
g = np.array([])
for i in p:
  print(i*2)

2
4
10


In [ ]:
#manual method
c = a*b
print(c)
print(c.sum())

[3 8]
11


In [ ]:
# @ is also similar as dot product
f = a@b
print(f)

11


#speed test b/w array vs list

In [ ]:
#import a time calculator to see the variations
from timeit import default_timer as timer

#create to random array
a = np.random.randn(1000)
b = np.random.randn(1000)
#covert the above array in the form of list
c = list(a)
d = list (b)
t = 1000
def dot1():
  dot = 0
  for i in range(len(c)):
    dot += c[i]*d[i]
  return dot
def dot2():
    return np.dot(a,b)
# take the timer
start = timer()
for t in range(t):
  dot1()
end = timer()
t1 = end-start

start = timer()
for t in range(t):
  dot2()
end = timer()
t2 = end-start

print("time with list",t1)
print("time with array",t2)

print("ratio",t1/t2)

time with list 0.24007763300005536
time with array 0.0017646100000092702
ratio 136.05138415785592


In [ ]:
#import a time calculator to see the variations
from timeit import default_timer as timer

#create to random array
a = np.random.randn(1000)
b = np.random.randn(1000)
#covert the above array in the form of tuple
c = tuple(a)
d = tuple(b)
t = 1000
def dot1():
  dot = 0
  for i in range(len(c)):
    dot += c[i]*d[i]
  return dot
def dot2():
    return np.dot(a,b)
# take the timer
start = timer()
for t in range(t):
  dot1()
end = timer()
t1 = end-start

start = timer()
for t in range(t):
  dot2()
end = timer()
t2 = end-start

print("time with tuple",t1)
print("time with array",t2)

print("ratio",t1/t2)

time with tuple 0.20167522299971097
time with array 0.001312581000092905
ratio 153.64783048469872


In [ ]:
s1 = {1,2,3,4}
a = np.array(s1)
print(a)  # we cannot convert set into array because set are immutable

{1, 2, 3, 4}


**mutlidimentional array**

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# how can we acess element from the 2d array
#print the entire row?
#a[row index number]
print(a[0])
print(a[1])
#how to acess the va;ue from particular column
# a[row index,column index]
print(a[0,0])
print(a[1,2])

[1 2 3]
[4 5 6]
1
6


In [ ]:
b = np.array([[1,2,3,],[4,5,6],[6,7,8]])
print(b)
#how can we print the entire values of col?
print(b[:,0])

[[1 2 3]
 [4 5 6]
 [6 7 8]]
[1 4 6]


In [ ]:
# how can i print entire  1st colm
b[0]
b[0,:]

array([1, 2, 3])

In [ ]:
# transpose:- it converts rows into columns and columns into rows
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# matrix multiplication
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
a@b

array([[13, 16],
       [29, 36]])

In [ ]:
# find the inverse
a = np.array([[1,2],[3,4]])
d = np.linalg.inv(a)
print(d)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#how can i find the diagonal of array a
e = np.diag(a)
print(e)

[1 4]


In [ ]:
# diagonal on vector returns the matrix
c = np.diag([1,3])
print(c)

[[1 0]
 [0 3]]


25-11-24

In [ ]:
  #generating a range of array up to 6
import numpy as np
a = np.arange(6)
  print(a)

[0 1 2 3 4 5]


In [ ]:
#convert the above array into rows and columns
b = a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [ ]:
#new axis :- it is used to create new axis
#why we are using np.newaxis?
#needed when model requires the data to be shaped in a certain manner

In [ ]:
#newaxis array into rows into columns
d = a[np.newaxis,:]
print(d)
d
d.shape

[[0 1 2 3 4 5]]


(1, 6)

In [ ]:
e = a[:,np.newaxis]
print(e)
e.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [ ]:
f = a.T
print(f.shape)#in transpose we can not applicable on 2D arrays only

(6,)


In [ ]:
a = np.arange(6)
b = a.reshape((2,3))
print(b)

[[0 1 2]
 [3 4 5]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
#combine or concatinate the above 2 array in to 1D
c = np.concatenate((a,b),axis=None)
print(c)

[1 2 3 4 5 6]


In [ ]:
#add new rows
d = np.concatenate((a,b),axis=0)
print(d)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(b)
print(b.T)

[[5 6]]
[[5]
 [6]]


In [ ]:
#add new column :note that we have to transpose the array b
e = np.concatenate((a,b.T),axis=1)
print(e)
e

[[1 2 5]
 [3 4 6]]


array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[5,6]])
h = np.concatenate((a,b),axis=1)
print(h)
print(h[0,:])

[[1 2 4 5]
 [3 4 5 6]]
[1 2 4 5]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[5,6]])
h = np.concatenate((a,b),axis=0)
print(h)

[[1 2]
 [3 4]
 [4 5]
 [5 6]]


In [ ]:
#how can i print the values of the 1st row
print(h[0,:])
print([0])

[1 2]
[0]


#Hstack

In [ ]:
#hstack : stack array in sequence horizontally(column wise)
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
#c = np.concatenate((a,b),axis=None)
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [ ]:
a = np.array([[1,2],[3,4]]) #applying hstack on 2D
b = np.array([[4,5],[5,6]])
c =np.hstack((a,b))
c

array([[1, 2, 4, 5],
       [3, 4, 5, 6]])

#Vstack

In [ ]:
#vstack:- stack array in sequence vertically(row wise)
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.vstack((a,b))
c


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a = np.array([[1,2],[3,4]]) #applying vstack on 2D
b = np.array([[4,5],[5,6]])
c = np.vstack((a,b))
c

array([[1, 2],
       [3, 4],
       [4, 5],
       [5, 6]])

#Broadcasting

In [ ]:
#it is an operation which deal with an different operations of an array

In [ ]:
x = np.array([[1,2,3],[4,5,6],[6,7,8],[8,9,7]])  #Broadcasting is a powerfull mechanisms that allows the numpy to thik with different arrays of different shapes when performing the arithematic operations
y = np.array([[1,2,0]])
z = x+y
print(z)

[[ 2  4  3]
 [ 5  7  6]
 [ 7  9  8]
 [ 9 11  7]]


#copying

In [ ]:
a = np.array([1,2,3,4])
b = a   #only copies the reference
b[0] = 42
print(b)

[1 2 3 4]
[42  2  3  4]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 7
print(a)
print(b)
#using  copy() if you make changes in any array the new array but the old array doesn't changes

[1 2 3]
[7 2 3]


#Data types

In [ ]:
a= np.dtype()

TypeError: Cannot construct a dtype from an array

In [ ]:
#how can we find the datatpe of an array means
a = np.array([1,2,3],dtype=np.int32)
a.dtype

dtype('int32')

In [ ]:
b = np.array([1.0,3.5],dtype=np.float32)
b.dtype

dtype('float32')

#Generating array's

In [ ]:
#generate an array as zeros which is having 2 rows and 3 columns
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [ ]:
#generate an array of specific value with specific rows and columns
c = np.full((3,4),7)
print(c)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
c = np.full((3,3),5)
print(c)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
f = np.ones((6,6))
f[1:-1,1:-1] = 0
print(f)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
#generate an identity matrix
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
## generate a range of numbers 10
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
###linspace splits the data into specific partsequally
#linspace(start,end,no of partitions)
#note:-- end will not changed
e = np.linspace(0,10,6)
print(e)

[ 0.  2.  4.  6.  8. 10.]


In [ ]:
#random numbers
#linear algebra
#solving the linear system
#load a csv file numpy

In [ ]:
a = int(input("enter any number n "))
factorial=[]
for i in range(1,a+1):
 if i%a == 0:
  print(i)
 i += 1
 factorial.append(i)
else:
  print(1)


enter any number n 8
8
1
